services:
  backend:
    secrets:
      - admin_token
      - session_secret
      - ask_answer_webhook_secret
      - n8n_token
      - google_client_secret
      - discord_bot_token
      - discord_webhook_url
      - smtp_user
      - smtp_pass
      - llm_api_key
      - local_llm_api_key
      - proxmox_api_token
      - unifi_api_key
      - homeassistant_token
      - plex_token
      - overseerr_api_key
      - tautulli_api_key
      - radarr_api_key
      - sonarr_api_key
    environment:
      ADMIN_TOKEN_FILE: /run/secrets/admin_token
      SESSION_SECRET_FILE: /run/secrets/session_secret
      ASK_ANSWER_WEBHOOK_SECRET_FILE: /run/secrets/ask_answer_webhook_secret
      N8N_TOKEN_FILE: /run/secrets/n8n_token
      GOOGLE_CLIENT_SECRET_FILE: /run/secrets/google_client_secret
      DISCORD_BOT_TOKEN_FILE: /run/secrets/discord_bot_token
      DISCORD_WEBHOOK_URL_FILE: /run/secrets/discord_webhook_url
      SMTP_USER_FILE: /run/secrets/smtp_user
      SMTP_PASS_FILE: /run/secrets/smtp_pass
      LLM_API_KEY_FILE: /run/secrets/llm_api_key
      LOCAL_LLM_API_KEY_FILE: /run/secrets/local_llm_api_key
      PROXMOX_API_TOKEN_FILE: /run/secrets/proxmox_api_token
      UNIFI_API_KEY_FILE: /run/secrets/unifi_api_key
      HOMEASSISTANT_TOKEN_FILE: /run/secrets/homeassistant_token
      PLEX_TOKEN_FILE: /run/secrets/plex_token
      OVERSEERR_API_KEY_FILE: /run/secrets/overseerr_api_key
      TAUTULLI_API_KEY_FILE: /run/secrets/tautulli_api_key
      RADARR_API_KEY_FILE: /run/secrets/radarr_api_key
      SONARR_API_KEY_FILE: /run/secrets/sonarr_api_key

secrets:
  admin_token:
    file: ./secrets/ADMIN_TOKEN
  session_secret:
    file: ./secrets/SESSION_SECRET
  ask_answer_webhook_secret:
    file: ./secrets/ASK_ANSWER_WEBHOOK_SECRET
  n8n_token:
    file: ./secrets/N8N_TOKEN
  google_client_secret:
    file: ./secrets/GOOGLE_CLIENT_SECRET
  discord_bot_token:
    file: ./secrets/DISCORD_BOT_TOKEN
  discord_webhook_url:
    file: ./secrets/DISCORD_WEBHOOK_URL
  smtp_user:
    file: ./secrets/SMTP_USER
  smtp_pass:
    file: ./secrets/SMTP_PASS
  llm_api_key:
    file: ./secrets/LLM_API_KEY
  local_llm_api_key:
    file: ./secrets/LOCAL_LLM_API_KEY
  proxmox_api_token:
    file: ./secrets/PROXMOX_API_TOKEN
  unifi_api_key:
    file: ./secrets/UNIFI_API_KEY
  homeassistant_token:
    file: ./secrets/HOMEASSISTANT_TOKEN
  plex_token:
    file: ./secrets/PLEX_TOKEN
  overseerr_api_key:
    file: ./secrets/OVERSEERR_API_KEY
  tautulli_api_key:
    file: ./secrets/TAUTULLI_API_KEY
  radarr_api_key:
    file: ./secrets/RADARR_API_KEY
  sonarr_api_key:
    file: ./secrets/SONARR_API_KEY
